[2025-06-02T04:13:25.310881] [Main execution] Error occurred: ConfigError: Failed to create loss function from config: {'_target_': 'src.training.losses.BCEDiceLoss', 'config': {'_target_': 'src.training.losses.bce_dice_loss.BCEDiceLossConfig', 'bce_weight': '${thresholds.loss_weight}', 'dice_weight': '${thresholds.loss_weight}', 'dice_smooth': 1.0, 'dice_sigmoid': True, 'dice_eps': 1e-06, 'bce_reduction': 'mean'}}
Details: Key 'bce_pos_weight' is not in struct
    full_key: training.loss.config.bce_pos_weight
    object_type=dict
Traceback:
Traceback (most recent call last):
  File "C:\Users\fgrv\OneDrive\Documentos\PythonProjects\doctorado\crackseg\src\utils\factory\factory.py", line 143, in get_loss_fn
    return cast(TypingCallable[..., object], BCEDiceLoss(**params))
                                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\OneDrive\Documentos\PythonProjects\doctorado\crackseg\src\training\losses\bce_dice_loss.py", line 59, in __init__
    "weight": config.bce_pos_weight,
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\fgrv\miniconda3\envs\torch\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
omegaconf.errors.ConfigAttributeError: Key 'bce_pos_weight' is not in struct
    full_key: training.loss.config.bce_pos_weight
    object_type=dict. Did you mean: 'bce_weight'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fgrv\OneDrive\Documentos\PythonProjects\doctorado\crackseg\src\main.py", line 786, in main
    metrics, optimizer, loss_fn = _setup_training_components(cfg, model)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\OneDrive\Documentos\PythonProjects\doctorado\crackseg\src\main.py", line 468, in _setup_training_components
    potential_loss_fn = get_loss_fn(cfg.training.loss)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fgrv\OneDrive\Documentos\PythonProjects\doctorado\crackseg\src\utils\factory\factory.py", line 155, in get_loss_fn
    raise ConfigError(
src.utils.core.exceptions.ConfigError: Failed to create loss function from config: {'_target_': 'src.training.losses.BCEDiceLoss', 'config': {'_target_': 'src.training.losses.bce_dice_loss.BCEDiceLossConfig', 'bce_weight': '${thresholds.loss_weight}', 'dice_weight': '${thresholds.loss_weight}', 'dice_smooth': 1.0, 'dice_sigmoid': True, 'dice_eps': 1e-06, 'bce_reduction': 'mean'}}
Details: Key 'bce_pos_weight' is not in struct
    full_key: training.loss.config.bce_pos_weight
    object_type=dict

--- --- ---
